# Alacritty Configuration (TOML)

general.import = ["./gruvbox-dark.toml"]
general.live_config_reload = true

[window]
opacity = 0.999
blur = true
decorations = "none"
dynamic_padding = false
dimensions = { columns = 180, lines = 45 }

[window.padding]
x = 10
y = 10

[font]
size = 10
normal.family = "JetBrains Mono Nerd Font"
normal.style = "Medium"
bold.family = "JetBrains Mono Nerd Font"
bold.style = "Bold"
italic.family = "JetBrains Mono Nerd Font"
italic.style = "MediumItalic"
bold_italic.family = "JetBrains Mono Nerd Font"
bold_italic.style = "BoldItalic"
